site_name: bfg9000
docs_dir: doc
repo_url: https://github.com/jimporter/bfg9000/
edit_uri: ""
copyright: Copyright &copy; 2015-2025 Jim Porter

theme: yeti-classic
extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: ยง
plugins:
  - search
  - macros:
      module_name: mkdocs

nav:
  - Home: index.md
  - User Guide:
    - Features: user/features.md
    - Getting Started: user/getting-started.md
    - Building with bfg9000: user/building.md
    - Writing a Build File: user/writing.md
  - Developer Guide:
    - Contributing: developer/contributing.md
    - Build Backends: developer/backends.md
    - Build Tools: developer/tools.md
    - Builtins: developer/builtins.md
  - Reference:
    - Builtin Functions: reference/builtins.md
    - Command-Line Interface: reference/command-line.md
    - Supported Languages: reference/languages.md
    - Environment Variables: reference/environment-vars.md
  - About:
    - Changes: about/changes.md
    - License: about/license.md
